### ISSUE TITLE
Error (409) when parsing YouTube account or playlist

### ISSUE THREAD

**Issue by pmd2016** [madiele/vod2pod-rss#71]
Brilliant work, this! Was really looking for a solution like this!

I just started the service on a Raspberry Pi, but I can't get it to work. Every time I submit a YouTube account or playlist I get this error message:

```
2023-05-07T18:19:01.758Z ERROR [app] could not translate rss
2023-05-07T18:19:01.759Z ERROR [app] could not parse rss, reason: unable to parse feed: no root element
```

I'm not sure where to look to solve this issue, do you have an idea where I could start?

**Comment by madiele** [comment]
can you pass me the url you are trying to input? if you don't want to share it in public send it to my email madiele92@gmail.com

also do you have a youtube api key set?

**Comment by pmd2016** [comment]
It doesn't really matter what url I'm trying, I tried with several accounts, for example: https://www.youtube.com/@DisneyNL, https://www.youtube.com/@Formula1.

Yes, I set up a YT API key. The API container is stopped immediately after setting it up. Is that supposed to happen?

**Comment by madiele** [comment]
> The API container is stopped immediately after setting it up. Is that supposed to happen?

yes

I'll see if I can replicate it and report back

**Comment by pmd2016** [comment]
O, wait! It just started working!

**Comment by madiele** [comment]
I was able to replicate your issue by setting an invalid youtube apikey, so my guess it was some problem related to that.

I should definitely try to improve error messaging to check if the apikey works though!

feel free to close the issue, or I will close it myself in a few days if the problem does not shows up.

**Comment by pmd2016** [comment]
Yeah, I think it had something to do with the API key.

I'll close this issue!

**Comment by BubiBalboa** [comment]
I also get the 409 error when I try to use an API key. Work fine without it, limitations aside. 

Just to make sure I'm doing it right: Are we supposed to paste the key after the = ? Or are we replacing everything that comes after the =  with the API key?

**Comment by madiele** [comment]
This is the correct syntax (using random characters instead of the api key) 


`      - YT_API_KEY=djsnidmsoeksnsjsodnedox9`

**Comment by BubiBalboa** [comment]
Thanks for quick response!

Okay, I changed it and did the "sudo docker compose up -d" thing. When everything is green I should be good to go, right? 

I tried it once and got a new error, which is fun. 

"Error 400: relative URL without a base"

Tried it again and got 409 again. Any ideas what could be going on?

**Comment by madiele** [comment]
I'm thinking your api key is not working right maybe it does not have the
right permissions, try to get a new one.

Also do a "sudo docker compose pull" too, to download any updates if are
there (I released a new version few days ago)

If nothing works, set the rust logs setting on the docker compose to
"DEBUG" and post here the logs "sudo docker compose logs" (check if you
need to remove any sensitive data before posting it)

**Comment by BubiBalboa** [comment]
Both the old and the new key are unrestricted. Are there other permissions I need to check? 

I freshly installed Docker to try your app, so it should be the latest version. 

I have Docker running in a container in Docker. I don't think this should be problem but I'm mentioning it just in case. It works fine without the API key. 

I'm working on getting the logs.

**Comment by madiele** [comment]
![Screenshot_20230910-203808_Firefox Nightly~2.png](https://github.com/madiele/vod2pod-rss/assets/4585690/aac91f59-3843-4f49-b6d5-695103ad6352)

Try this settings

**Comment by madiele** [comment]
Also give me an example of the inputs you are trying, I will test them in my own instance

**Comment by BubiBalboa** [comment]
I got the 409 error again. I really thought the change to the Youtube API would to the trick. :/ I waited at least ten minutes for the change to take effect. And I double checked that I'm using the correct key in the config file. I hope I can rule out easy errors. 

I'm just posting random channels into the text box. "https://www.youtube.com/@TomScottGo" for example.

**Comment by madiele** [comment]
Can confirm the link works on my end with the api key... 

can you post your docker-compose file with sensitive data obscured so that I can see if something is weird?

**Comment by BubiBalboa** [comment]
He are some logs, not sure if that is detailed enough. I don't think the memory thing is the problem. 

```
root@pDocker:~/vod2pod-rss# docker compose logs -t -f --tail 5
vod2pod-rss-vod2pod-1  | 2023-09-10T19:14:08.883512192Z 2023-09-10T19:14:08.883Z ERROR [app] could not parse rss, reason: unable to parse feed: no root element
vod2pod-rss-vod2pod-1  | 2023-09-10T19:14:36.727569556Z 2023-09-10T19:14:36.715Z INFO  [vod2pod_rss::provider::youtube] trying to convert youtube channel url https://www.youtube.com/@patrickwillemspresents1220
vod2pod-rss-vod2pod-1  | 2023-09-10T19:14:36.727638329Z 2023-09-10T19:14:36.716Z INFO  [vod2pod_rss::provider::youtube] conversion not in cache, using yt-dlp for conversion...
vod2pod-rss-vod2pod-1  | 2023-09-10T19:14:41.077220917Z 2023-09-10T19:14:41.076Z ERROR [app] could not translate rss
vod2pod-rss-vod2pod-1  | 2023-09-10T19:14:41.077261706Z 2023-09-10T19:14:41.076Z ERROR [app] could not parse rss, reason: unable to parse feed: no root element
vod2pod-rss-podtube-1  | 2023-09-10T19:14:03.025979802Z 2023-09-10 19:14:03,025 [ERROR] 500 GET /youtube/channel/UCQHX6ViZmPsWiYSFAyS0a3Q (172.18.0.3) 296.91ms
vod2pod-rss-podtube-1  | 2023-09-10T19:14:08.881151722Z 2023-09-10 19:14:08,880 [ERROR] Error Downloading Channel: Forbidden
vod2pod-rss-podtube-1  | 2023-09-10T19:14:08.883933271Z 2023-09-10 19:14:08,883 [ERROR] 500 GET /youtube/channel/UCXuqSBlHAE6Xw-yeJA0Tunw (172.18.0.3) 325.30ms
vod2pod-rss-podtube-1  | 2023-09-10T19:14:41.074957200Z 2023-09-10 19:14:41,074 [ERROR] Error Downloading Channel: Forbidden
vod2pod-rss-podtube-1  | 2023-09-10T19:14:41.077984236Z 2023-09-10 19:14:41,077 [ERROR] 500 GET /youtube/channel/UCMAwBUlaxyqZY-2hVac8qgg (172.18.0.3) 781.02ms
twitchToPodcastRSS     | 2023-09-10T19:17:58.209309410Z     raise Exception("Twitch API client id env variable is not set.")
twitchToPodcastRSS     | 2023-09-10T19:17:58.209315473Z Exception: Twitch API client id env variable is not set.
twitchToPodcastRSS     | 2023-09-10T19:17:58.209732839Z [2023-09-10 20:17:58 +0100] [8] [info] Worker exiting (pid: 8)
twitchToPodcastRSS     | 2023-09-10T19:17:58.311808344Z [2023-09-10 20:17:58 +0100] [6] [INFO] Shutting down: Master
twitchToPodcastRSS     | 2023-09-10T19:17:58.312038225Z [2023-09-10 20:17:58 +0100] [6] [INFO] Reason: Worker failed to boot.
vod2pod-rss-redis-1    | 2023-09-10T13:31:10.054013299Z 1:C 10 Sep 2023 13:31:10.052 # oO0OoO0OoO0Oo Redis is starting oO0OoO0OoO0Oo
vod2pod-rss-redis-1    | 2023-09-10T13:31:10.054080772Z 1:C 10 Sep 2023 13:31:10.052 # Redis version=6.2.13, bits=64, commit=00000000, modified=0, pid=1, just started
vod2pod-rss-redis-1    | 2023-09-10T13:31:10.054094658Z 1:C 10 Sep 2023 13:31:10.052 # Configuration loaded
vod2pod-rss-redis-1    | 2023-09-10T13:31:10.062872486Z 1:M 10 Sep 2023 13:31:10.054 # Server initialized
vod2pod-rss-redis-1    | 2023-09-10T13:31:10.062907939Z 1:M 10 Sep 2023 13:31:10.054 # WARNING Memory overcommit must be enabled! Without it, a background save or replication may fail under low memory condition. Being disabled, it can can also cause failures without low memory condition, see https://github.com/jemalloc/jemalloc/issues/1328. To fix this issue add 'vm.overcommit_memory = 1' to /etc/sysctl.conf and then reboot or run the command 'sysctl vm.overcommit_memory=1' for this to take effect.
```

**Comment by BubiBalboa** [comment]
Do you mean the docker-compose.yml? Or something else?


```
services:
  api_keys:
    image: alpine
    environment:
    #add your api-keys here (put them after the "=" sign or use an .env file)
      # Set your YouTube API key
      - YT_API_KEY=XXXXXXXXXXXXXXXXXXXXXXXXXXXXX
      # Set your Twitch secret
      - TWITCH_SECRET=${TWITCH_SECRET:-}
      # Set your Twitch client ID
      - TWITCH_CLIENT_ID=${TWITCH_CLIENT_ID:-}

  vod2pod:
    extends: api_keys
    image: madiele/vod2pod-rss
    depends_on:
      - redis
    restart: unless-stopped
    ports:
      - "1234:8080" #change from 80 to another port if you already use the port 80 on your host
    environment:
```

**Comment by madiele** [comment]
Wait, where is the peertube service block?

If you check the docker-compose.yml in the repo you will see it, you have to add it back if you want the api key to work

**Comment by madiele** [comment]
I'm reopening the issue for the time being

**Comment by BubiBalboa** [comment]
Yeah, my bad on the yml file. I never scrolled down that far. I have now set the logs to debug as well. Didn't see that before. 

```
version: "3.9"

services:
  api_keys:
    image: alpine
    environment:
    #add your api-keys here (put them after the "=" sign or use an .env file)
      # Set your YouTube API key
      - YT_API_KEY=XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
      # Set your Twitch secret
      - TWITCH_SECRET=${TWITCH_SECRET:-}
      # Set your Twitch client ID
      - TWITCH_CLIENT_ID=${TWITCH_CLIENT_ID:-}

  vod2pod:
    extends: api_keys
    image: madiele/vod2pod-rss
    depends_on:
      - redis
    restart: unless-stopped
    ports:
      - "1234:8080" #change from 80 to another port if you already use the port 80 on your host
    environment:
      - TZ=Europe/London #set if you want the logs to have you timezone
      - MP3_BITRATE=192 #bitrate in kilobits of the mp3 transcode
      - TRANSCODE=true #put to false if you only need feed generation
      - SUBFOLDER=/ #for reverse proxies, ex: "/" -> access the app at mywebsite.com ; "vod2pod" -> access at mywebsite>
      - RUST_LOG=DEBUG #INFO #set to DEBUG if you are having problems than open a github issue with the logs, use "sudo>
      - TWITCH_TO_PODCAST_URL=ttprss #don't edit this
      - PODTUBE_URL=http://podtube:15000 #don't edit this
      - REDIS_ADDRESS=redis #don't edit this
      - REDIS_PORT=6379 #don't edit this

  ttprss: # you can remove this section and save some storage if you don't need twitch
    extends: api_keys
    image: madiele/twitch_to_podcast_rss
    restart: unless-stopped
    container_name: twitchToPodcastRSS
    environment:
        - TZ=Europe/London
        - TRANSCODE=False #keep this to false, the vod2pod one is the one you should change

  podtube: #remove this section if you don't need improved youtube support
    extends: api_keys
    image: ftawesome/podtube
    restart: unless-stopped
    environment:
      - YT_AUTOLOAD_NEWEST_AUDIO=False

  redis:
    image: "redis:6.2"
    command: redis-server --save 20 1 --loglevel warning
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "redis-cli ping | grep PONG"]
      interval: 10s
      timeout: 3s
      retries: 5
```
